package uk.gov.digital.ho.hocs.document.application

enum class LogEvent {
    DOCUMENT_CREATED,
    DOCUMENT_CREATION_FAILURE,
    DOCUMENT_CONVERSION_FAILURE,
    DOCUMENT_DELETED,
    DOCUMENT_UPDATED,
    DOCUMENT_UPDATE_FAILURE,
    DOCUMENT_NOT_FOUND,
    DOCUMENT_VIRUS_SCAN_FAILURE,
    DOCUMENT_CLIENT_PROCESS_SUCCESS,
    DOCUMENT_CLIENT_FAILURE,
    DOCUMENT_DATA_REQUEST,
    DOCUMENT_FILELINK_MISSING,
    S3_DOWNLOAD_FAILURE,
    S3_UPLOAD_FAILURE,
    S3_TRUSTED_COPY_REQUEST,
    S3_FILE_NOT_FOUND,
    AUDIT_EVENT_CREATED,
    AUDIT_FAILED,
    UNCAUGHT_EXCEPTION;

    companion object {
        const val EVENT = "event_id"
    }
}